baseurl = "http://xiaomingplus.com/"
title = "小明plus"
Paginate = 20
theme= "we"
hasCJKLanguage = true
[[menu.main]]
    name = "关于我"
    identifier = "about"
    url = "/about"
[params]
  disqusShortname = "xiaomingplus"
